AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Database Migration
  RDS PostgreSQL

Resources:
  PostgreSQL:
    Type: 'AWS::RDS::DBInstance'
    Properties:
    #Engine Options
      Engine: postgres
      EngineVersion: 13.4
    #Templates
    #Settings
      DBInstanceIdentifier: targetdb
      MasterUsername: postgres
      MasterUserPassword: target1234
    #DB instance class
      DBInstanceClass: db.t3.micro
    #Storage
      StorageType: gp2
      AllocatedStorage: 20
      MaxAllocatedStorage: 1000
    #Availability & durability
      MultiAZ: false
    #Connectivity
      #DBSubnetGroupName
      PubliclyAccessible: true
      #VPCSecurityGroups:
      #AvailabilityZone:
      Port: 45432
    #Database authentication 
      EnableIAMDatabaseAuthentication: false
    #Configuration
      DBName: postgres
      DBParameterGroupName: default.postgres13
      BackupRetentionPeriod: 0
      StorageEncrypted: false
      EnablePerformanceInsights: false
      MonitoringInterval: 0
      #EnableCloudwatchLogsExports: 
      #  - postgresql
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DeletionProtection: false